/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as NhsRouteImport } from './routes/nhs'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppCredentialsRouteImport } from './routes/app.credentials'
import { Route as AppDidsRouteImport } from './routes/app.dids'
import { Route as AppSandboxRouteImport } from './routes/app.sandbox'
import { Route as AppZkRouteImport } from './routes/app.zk'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicA2aSellerRouteImport } from './routes/api/public/a2a-seller'
import { Route as ApiPublicUcpMerchantRouteImport } from './routes/api/public/ucp-merchant'
import { Route as ApiPublicX402ProxyRouteImport } from './routes/api/public/x402-proxy'
import { Route as AppDemosIndexRouteImport } from './routes/app.demos.index'
import { Route as AppDemosA2aRouteImport } from './routes/app.demos.a2a'
import { Route as AppDemosAp2RouteImport } from './routes/app.demos.ap2'
import { Route as AppDemosUcpRouteImport } from './routes/app.demos.ucp'
import { Route as AppDemosX402RouteImport } from './routes/app.demos.x402'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const NhsRoute = NhsRouteImport.update({
  id: '/nhs',
  path: '/nhs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsRoute = AppCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AppRoute,
} as any)
const AppDidsRoute = AppDidsRouteImport.update({
  id: '/dids',
  path: '/dids',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxRoute = AppSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AppRoute,
} as any)
const AppZkRoute = AppZkRouteImport.update({
  id: '/zk',
  path: '/zk',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicA2aSellerRoute = ApiPublicA2aSellerRouteImport.update({
  id: '/api/public/a2a-seller',
  path: '/api/public/a2a-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUcpMerchantRoute = ApiPublicUcpMerchantRouteImport.update({
  id: '/api/public/ucp-merchant',
  path: '/api/public/ucp-merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicX402ProxyRoute = ApiPublicX402ProxyRouteImport.update({
  id: '/api/public/x402-proxy',
  path: '/api/public/x402-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDemosIndexRoute = AppDemosIndexRouteImport.update({
  id: '/demos/',
  path: '/demos/',
  getParentRoute: () => AppRoute,
} as any)
const AppDemosA2aRoute = AppDemosA2aRouteImport.update({
  id: '/demos/a2a',
  path: '/demos/a2a',
  getParentRoute: () => AppRoute,
} as any)
const AppDemosAp2Route = AppDemosAp2RouteImport.update({
  id: '/demos/ap2',
  path: '/demos/ap2',
  getParentRoute: () => AppRoute,
} as any)
const AppDemosUcpRoute = AppDemosUcpRouteImport.update({
  id: '/demos/ucp',
  path: '/demos/ucp',
  getParentRoute: () => AppRoute,
} as any)
const AppDemosX402Route = AppDemosX402RouteImport.update({
  id: '/demos/x402',
  path: '/demos/x402',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRoute
  '/learn': typeof LearnRoute
  '/nhs': typeof NhsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/credentials': typeof AppCredentialsRoute
  '/app/dids': typeof AppDidsRoute
  '/app/sandbox': typeof AppSandboxRoute
  '/app/zk': typeof AppZkRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/api/public/a2a-seller': typeof ApiPublicA2aSellerRoute
  '/api/public/ucp-merchant': typeof ApiPublicUcpMerchantRoute
  '/api/public/x402-proxy': typeof ApiPublicX402ProxyRoute
  '/app/demos/a2a': typeof AppDemosA2aRoute
  '/app/demos/ap2': typeof AppDemosAp2Route
  '/app/demos/ucp': typeof AppDemosUcpRoute
  '/app/demos/x402': typeof AppDemosX402Route
  '/app/demos/': typeof AppDemosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRoute
  '/learn': typeof LearnRoute
  '/nhs': typeof NhsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/credentials': typeof AppCredentialsRoute
  '/app/dids': typeof AppDidsRoute
  '/app/sandbox': typeof AppSandboxRoute
  '/app/zk': typeof AppZkRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
  '/api/public/a2a-seller': typeof ApiPublicA2aSellerRoute
  '/api/public/ucp-merchant': typeof ApiPublicUcpMerchantRoute
  '/api/public/x402-proxy': typeof ApiPublicX402ProxyRoute
  '/app/demos/a2a': typeof AppDemosA2aRoute
  '/app/demos/ap2': typeof AppDemosAp2Route
  '/app/demos/ucp': typeof AppDemosUcpRoute
  '/app/demos/x402': typeof AppDemosX402Route
  '/app/demos': typeof AppDemosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRoute
  '/learn': typeof LearnRoute
  '/nhs': typeof NhsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/credentials': typeof AppCredentialsRoute
  '/app/dids': typeof AppDidsRoute
  '/app/sandbox': typeof AppSandboxRoute
  '/app/zk': typeof AppZkRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/api/public/a2a-seller': typeof ApiPublicA2aSellerRoute
  '/api/public/ucp-merchant': typeof ApiPublicUcpMerchantRoute
  '/api/public/x402-proxy': typeof ApiPublicX402ProxyRoute
  '/app/demos/a2a': typeof AppDemosA2aRoute
  '/app/demos/ap2': typeof AppDemosAp2Route
  '/app/demos/ucp': typeof AppDemosUcpRoute
  '/app/demos/x402': typeof AppDemosX402Route
  '/app/demos/': typeof AppDemosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/docs'
    | '/learn'
    | '/nhs'
    | '/app/activity'
    | '/app/agents'
    | '/app/credentials'
    | '/app/dids'
    | '/app/sandbox'
    | '/app/zk'
    | '/auth/callback'
    | '/app/'
    | '/api/public/a2a-seller'
    | '/api/public/ucp-merchant'
    | '/api/public/x402-proxy'
    | '/app/demos/a2a'
    | '/app/demos/ap2'
    | '/app/demos/ucp'
    | '/app/demos/x402'
    | '/app/demos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/learn'
    | '/nhs'
    | '/app/activity'
    | '/app/agents'
    | '/app/credentials'
    | '/app/dids'
    | '/app/sandbox'
    | '/app/zk'
    | '/auth/callback'
    | '/app'
    | '/api/public/a2a-seller'
    | '/api/public/ucp-merchant'
    | '/api/public/x402-proxy'
    | '/app/demos/a2a'
    | '/app/demos/ap2'
    | '/app/demos/ucp'
    | '/app/demos/x402'
    | '/app/demos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/docs'
    | '/learn'
    | '/nhs'
    | '/app/activity'
    | '/app/agents'
    | '/app/credentials'
    | '/app/dids'
    | '/app/sandbox'
    | '/app/zk'
    | '/auth/callback'
    | '/app/'
    | '/api/public/a2a-seller'
    | '/api/public/ucp-merchant'
    | '/api/public/x402-proxy'
    | '/app/demos/a2a'
    | '/app/demos/ap2'
    | '/app/demos/ucp'
    | '/app/demos/x402'
    | '/app/demos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DocsRoute: typeof DocsRoute
  LearnRoute: typeof LearnRoute
  NhsRoute: typeof NhsRoute
  ApiPublicA2aSellerRoute: typeof ApiPublicA2aSellerRoute
  ApiPublicUcpMerchantRoute: typeof ApiPublicUcpMerchantRoute
  ApiPublicX402ProxyRoute: typeof ApiPublicX402ProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhs': {
      id: '/nhs'
      path: '/nhs'
      fullPath: '/nhs'
      preLoaderRoute: typeof NhsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/credentials': {
      id: '/app/credentials'
      path: '/credentials'
      fullPath: '/app/credentials'
      preLoaderRoute: typeof AppCredentialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dids': {
      id: '/app/dids'
      path: '/dids'
      fullPath: '/app/dids'
      preLoaderRoute: typeof AppDidsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sandbox': {
      id: '/app/sandbox'
      path: '/sandbox'
      fullPath: '/app/sandbox'
      preLoaderRoute: typeof AppSandboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/zk': {
      id: '/app/zk'
      path: '/zk'
      fullPath: '/app/zk'
      preLoaderRoute: typeof AppZkRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/a2a-seller': {
      id: '/api/public/a2a-seller'
      path: '/api/public/a2a-seller'
      fullPath: '/api/public/a2a-seller'
      preLoaderRoute: typeof ApiPublicA2aSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ucp-merchant': {
      id: '/api/public/ucp-merchant'
      path: '/api/public/ucp-merchant'
      fullPath: '/api/public/ucp-merchant'
      preLoaderRoute: typeof ApiPublicUcpMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402-proxy': {
      id: '/api/public/x402-proxy'
      path: '/api/public/x402-proxy'
      fullPath: '/api/public/x402-proxy'
      preLoaderRoute: typeof ApiPublicX402ProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/demos/': {
      id: '/app/demos/'
      path: '/demos'
      fullPath: '/app/demos/'
      preLoaderRoute: typeof AppDemosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demos/a2a': {
      id: '/app/demos/a2a'
      path: '/demos/a2a'
      fullPath: '/app/demos/a2a'
      preLoaderRoute: typeof AppDemosA2aRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demos/ap2': {
      id: '/app/demos/ap2'
      path: '/demos/ap2'
      fullPath: '/app/demos/ap2'
      preLoaderRoute: typeof AppDemosAp2RouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demos/ucp': {
      id: '/app/demos/ucp'
      path: '/demos/ucp'
      fullPath: '/app/demos/ucp'
      preLoaderRoute: typeof AppDemosUcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demos/x402': {
      id: '/app/demos/x402'
      path: '/demos/x402'
      fullPath: '/app/demos/x402'
      preLoaderRoute: typeof AppDemosX402RouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppCredentialsRoute: typeof AppCredentialsRoute
  AppDidsRoute: typeof AppDidsRoute
  AppSandboxRoute: typeof AppSandboxRoute
  AppZkRoute: typeof AppZkRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDemosA2aRoute: typeof AppDemosA2aRoute
  AppDemosAp2Route: typeof AppDemosAp2Route
  AppDemosUcpRoute: typeof AppDemosUcpRoute
  AppDemosX402Route: typeof AppDemosX402Route
  AppDemosIndexRoute: typeof AppDemosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppCredentialsRoute: AppCredentialsRoute,
  AppDidsRoute: AppDidsRoute,
  AppSandboxRoute: AppSandboxRoute,
  AppZkRoute: AppZkRoute,
  AppIndexRoute: AppIndexRoute,
  AppDemosA2aRoute: AppDemosA2aRoute,
  AppDemosAp2Route: AppDemosAp2Route,
  AppDemosUcpRoute: AppDemosUcpRoute,
  AppDemosX402Route: AppDemosX402Route,
  AppDemosIndexRoute: AppDemosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DocsRoute: DocsRoute,
  LearnRoute: LearnRoute,
  NhsRoute: NhsRoute,
  ApiPublicA2aSellerRoute: ApiPublicA2aSellerRoute,
  ApiPublicUcpMerchantRoute: ApiPublicUcpMerchantRoute,
  ApiPublicX402ProxyRoute: ApiPublicX402ProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
